-- MySQL Script generated by MySQL Workbench
-- 01/11/17 20:01:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema deliverydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deliverydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deliverydb` DEFAULT CHARACTER SET utf8 ;
USE `deliverydb` ;

-- -----------------------------------------------------
-- Table `deliverydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Categoria` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nombre` VARCHAR(45) NULL,
  `cat_descripcion` TEXT NULL,
  `cat_idEstado` INT NULL,
  `cat_imagen` VARCHAR(120) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `cuilt` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `logo` VARCHAR(120) NULL,
  `razonSocial` VARCHAR(45) NULL,
  `Imagen` VARCHAR(120) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Sucursal` (
  `suc_id` INT NOT NULL,
  `suc_nombre` VARCHAR(45) NULL,
  `suc_cuit` VARCHAR(45) NULL,
  `suc_razonSocial` VARCHAR(45) NULL,
  `suc_idEmpresa` INT NOT NULL,
  `suc_direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`suc_id`),
  INDEX `fk_Sucursal_Empresa1_idx` (`suc_idEmpresa` ASC),
  CONSTRAINT `fk_Sucursal_Empresa1`
    FOREIGN KEY (`suc_idEmpresa`)
    REFERENCES `deliverydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Producto` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_idCategoria` INT NOT NULL,
  `prod_codigoProducto` VARCHAR(45) NULL,
  `prod_nombre` VARCHAR(45) NULL,
  `prod_descripcionProducto` TEXT NULL,
  `prod_precioBase` FLOAT NULL,
  `prod_maxComponente` INT NULL,
  `prod_minComponente` INT NULL,
  `prod_idEstado` INT NULL,
  `prod_idEstadoVisible` INT NULL,
  `prod_idSucursal` INT NOT NULL,
  INDEX `fk_Producto_Categoria_idx` (`prod_idCategoria` ASC),
  PRIMARY KEY (`prod_id`),
  INDEX `fk_Producto_Sucursal1_idx` (`prod_idSucursal` ASC),
  CONSTRAINT `fk_Producto_Categoria0`
    FOREIGN KEY (`prod_idCategoria`)
    REFERENCES `deliverydb`.`Categoria` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Sucursal1`
    FOREIGN KEY (`prod_idSucursal`)
    REFERENCES `deliverydb`.`Sucursal` (`suc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Variedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Variedad` (
  `var_id` INT NOT NULL AUTO_INCREMENT,
  `var_idProducto` INT NOT NULL,
  `var_nombre` VARCHAR(45) NULL,
  `var_descripcion` TEXT NULL,
  `var_tipo` VARCHAR(45) NULL,
  `var_precio` FLOAT NULL,
  PRIMARY KEY (`var_id`),
  INDEX `fk_Variedad_Producto1_idx` (`var_idProducto` ASC),
  CONSTRAINT `fk_Variedad_Producto1`
    FOREIGN KEY (`var_idProducto`)
    REFERENCES `deliverydb`.`Producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Componente` (
  `com_id` INT NOT NULL AUTO_INCREMENT,
  `com_precio` FLOAT NOT NULL,
  `com_idEstado` INT NOT NULL,
  `com_Nombre` VARCHAR(45) NULL,
  `com_descripcion` TEXT NULL,
  `com_imagen` VARCHAR(120) NULL,
  PRIMARY KEY (`com_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`ComponenteProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`ComponenteProducto` (
  `cp_id` INT NOT NULL AUTO_INCREMENT,
  `cp_idProducto` INT NOT NULL,
  `cp_idComponente` INT NOT NULL,
  PRIMARY KEY (`cp_id`),
  INDEX `fk_ComponenteProducto_Producto1_idx` (`cp_idProducto` ASC),
  INDEX `fk_ComponenteProducto_Componente1_idx` (`cp_idComponente` ASC),
  CONSTRAINT `fk_ComponenteProducto_Producto1`
    FOREIGN KEY (`cp_idProducto`)
    REFERENCES `deliverydb`.`Producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComponenteProducto_Componente1`
    FOREIGN KEY (`cp_idComponente`)
    REFERENCES `deliverydb`.`Componente` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`ProductoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`ProductoPedido` (
  `pp_id` INT NOT NULL AUTO_INCREMENT,
  `pp_precioBase` FLOAT NULL,
  `pp_idProducto` INT NOT NULL,
  `pp_idVariedad` INT NOT NULL,
  `pp_precioCalc` FLOAT NULL,
  PRIMARY KEY (`pp_id`),
  INDEX `fk_ProductoPedido_Producto1_idx` (`pp_idProducto` ASC),
  INDEX `fk_ProductoPedido_Variedad1_idx` (`pp_idVariedad` ASC),
  CONSTRAINT `fk_ProductoPedido_Producto1`
    FOREIGN KEY (`pp_idProducto`)
    REFERENCES `deliverydb`.`Producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoPedido_Variedad1`
    FOREIGN KEY (`pp_idVariedad`)
    REFERENCES `deliverydb`.`Variedad` (`var_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Persona` (
  `pers_id` INT NOT NULL,
  `per_nombre` VARCHAR(45) NOT NULL,
  `per_email` VARCHAR(45) NOT NULL,
  `per_documento` VARCHAR(45) NULL,
  `per_password` VARCHAR(45) NULL,
  `per_nacionalidad` VARCHAR(45) NULL,
  `per_perfilUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`pers_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Cliente` (
  `cli_idPersona` INT NOT NULL,
  `cli_tel` VARCHAR(45) NOT NULL,
  `cli_direccion` VARCHAR(45) NULL,
  `cli_estado` VARCHAR(120) NULL,
  `cli_tipo` VARCHAR(45) NULL,
  `cli_cuit` VARCHAR(45) NULL,
  `cli_razonSocial` VARCHAR(45) NULL,
  `cli_direccionLegal` VARCHAR(45) NULL,
  PRIMARY KEY (`cli_idPersona`, `cli_tel`),
  INDEX `fk_Cliente_Persona1_idx` (`cli_idPersona` ASC),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`cli_idPersona`)
    REFERENCES `deliverydb`.`Persona` (`pers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`PedidoEncabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`PedidoEncabezado` (
  `pe_id` INT NOT NULL AUTO_INCREMENT,
  `pe_idCliente` VARCHAR(45) NULL,
  `pe_idEmpleado` VARCHAR(45) NULL,
  `pe_aclaraciones` TEXT NULL,
  `pe_comentarios` VARCHAR(45) NULL,
  `pe_idEstado` INT NULL,
  `pe_Total` FLOAT NULL,
  `Cliente_cli_idPersona` INT NOT NULL,
  `Cliente_cli_tel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pe_id`),
  UNIQUE INDEX `total_UNIQUE` (`pe_Total` ASC),
  INDEX `fk_PedidoEncabezado_Cliente1_idx` (`Cliente_cli_idPersona` ASC, `Cliente_cli_tel` ASC),
  CONSTRAINT `fk_PedidoEncabezado_Cliente1`
    FOREIGN KEY (`Cliente_cli_idPersona` , `Cliente_cli_tel`)
    REFERENCES `deliverydb`.`Cliente` (`cli_idPersona` , `cli_tel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`DetallePedido` (
  `dp_id` INT NOT NULL AUTO_INCREMENT,
  `dp_Cantidad` INT NOT NULL,
  `dp_PrecioUnitario` FLOAT NULL,
  `dp_Total` FLOAT NULL,
  `dp_idProductoPedido` INT NOT NULL,
  `dp_idPedidoEncabezado` INT NOT NULL,
  PRIMARY KEY (`dp_id`),
  INDEX `fk_DetallePedido_ProductoPedido1_idx` (`dp_idProductoPedido` ASC),
  INDEX `fk_DetallePedido_PedidoEncabezado1_idx` (`dp_idPedidoEncabezado` ASC),
  CONSTRAINT `fk_DetallePedido_ProductoPedido1`
    FOREIGN KEY (`dp_idProductoPedido`)
    REFERENCES `deliverydb`.`ProductoPedido` (`pp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_PedidoEncabezado1`
    FOREIGN KEY (`dp_idPedidoEncabezado`)
    REFERENCES `deliverydb`.`PedidoEncabezado` (`pe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`ComponentePPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`ComponentePPedido` (
  `cpp_id` INT NOT NULL AUTO_INCREMENT,
  `cpp_idProductoPedido` INT NOT NULL,
  `cpp_idComponente` INT NOT NULL,
  PRIMARY KEY (`cpp_id`),
  INDEX `fk_ComponentePPedido_ProductoPedido1_idx` (`cpp_idProductoPedido` ASC),
  INDEX `fk_ComponentePPedido_Componente1_idx` (`cpp_idComponente` ASC),
  CONSTRAINT `fk_ComponentePPedido_ProductoPedido1`
    FOREIGN KEY (`cpp_idProductoPedido`)
    REFERENCES `deliverydb`.`ProductoPedido` (`pp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComponentePPedido_Componente1`
    FOREIGN KEY (`cpp_idComponente`)
    REFERENCES `deliverydb`.`Componente` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Promo` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) NULL,
  `pro_descripcion` VARCHAR(45) NULL,
  `pro_precio` FLOAT NULL,
  `pro_descuento` FLOAT NULL,
  `pro_FechaInicio` DATE NULL,
  `pro_FechaFin` DATE NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`ProductoPromo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`ProductoPromo` (
  `ppro_id` INT NOT NULL AUTO_INCREMENT,
  `ppro_idPromo` INT NOT NULL,
  `ppro_idProducto` INT NOT NULL,
  PRIMARY KEY (`ppro_id`),
  INDEX `fk_ProductoPromo_Promo1_idx` (`ppro_idPromo` ASC),
  INDEX `fk_ProductoPromo_Producto1_idx` (`ppro_idProducto` ASC),
  CONSTRAINT `fk_ProductoPromo_Promo1`
    FOREIGN KEY (`ppro_idPromo`)
    REFERENCES `deliverydb`.`Promo` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoPromo_Producto1`
    FOREIGN KEY (`ppro_idProducto`)
    REFERENCES `deliverydb`.`Producto` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`PromoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`PromoPedido` (
  `ppro_id` INT NOT NULL AUTO_INCREMENT,
  `ppro_Nombre` VARCHAR(45) NULL,
  `ppro_PrecioUnitario` FLOAT NULL,
  `ppro_Cantidad` INT NULL,
  `ppro_Total` FLOAT NOT NULL,
  `ppro_PrecioBase` FLOAT NULL,
  `PedidoEncabezado_pe_id` INT NOT NULL,
  PRIMARY KEY (`ppro_id`),
  INDEX `fk_PromoPedido_PedidoEncabezado1_idx` (`PedidoEncabezado_pe_id` ASC),
  CONSTRAINT `fk_PromoPedido_PedidoEncabezado1`
    FOREIGN KEY (`PedidoEncabezado_pe_id`)
    REFERENCES `deliverydb`.`PedidoEncabezado` (`pe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`ListaProductoPromoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`ListaProductoPromoPedido` (
  `ppp_id` INT NOT NULL,
  `ppp_idProductoPedido` INT NOT NULL,
  `ppp_promoPedido` INT NOT NULL,
  PRIMARY KEY (`ppp_id`),
  INDEX `fk_ListaProductoPromoPedido_ProductoPedido1_idx` (`ppp_idProductoPedido` ASC),
  INDEX `fk_ListaProductoPromoPedido_PromoPedido1_idx` (`ppp_promoPedido` ASC),
  CONSTRAINT `fk_ListaProductoPromoPedido_ProductoPedido1`
    FOREIGN KEY (`ppp_idProductoPedido`)
    REFERENCES `deliverydb`.`ProductoPedido` (`pp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaProductoPromoPedido_PromoPedido1`
    FOREIGN KEY (`ppp_promoPedido`)
    REFERENCES `deliverydb`.`PromoPedido` (`ppro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`TablasRelacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`TablasRelacion` (
  `idEstado` INT NOT NULL,
  `relacion` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `orden` INT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`DiaHorario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`DiaHorario` (
  `dh_id` INT NOT NULL,
  `dh_diaSemana` VARCHAR(45) NULL,
  `dh_horaApertura` VARCHAR(45) NULL,
  `dh_horaCierre` VARCHAR(45) NULL,
  `Sucursal_suc_id` INT NOT NULL,
  `Sucursal_Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`dh_id`),
  INDEX `fk_DiaHorario_Sucursal1_idx` (`Sucursal_suc_id` ASC, `Sucursal_Empresa_idEmpresa` ASC),
  CONSTRAINT `fk_DiaHorario_Sucursal1`
    FOREIGN KEY (`Sucursal_suc_id`)
    REFERENCES `deliverydb`.`Sucursal` (`suc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Parametros` (
  `par_id` INT NOT NULL,
  `par_zonaEntrega` VARCHAR(45) NULL,
  `par_pedidoMinimo` FLOAT NULL,
  `par_tiempoEntrega` INT NULL,
  `par_costoEnvio` FLOAT NULL,
  `par_idSucursal` INT NOT NULL,
  PRIMARY KEY (`par_id`),
  INDEX `fk_Parametros_Sucursal1_idx` (`par_idSucursal` ASC),
  CONSTRAINT `fk_Parametros_Sucursal1`
    FOREIGN KEY (`par_idSucursal`)
    REFERENCES `deliverydb`.`Sucursal` (`suc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deliverydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliverydb`.`Empleado` (
  `pers_id` INT NOT NULL,
  `emp_legajo` VARCHAR(45) NULL,
  `emp_idPersona` INT NOT NULL,
  `emp_imagen` VARCHAR(120) NOT NULL,
  `emp_cargo` VARCHAR(45) NULL,
  `emp_idSucursal` INT NOT NULL,
  PRIMARY KEY (`pers_id`),
  INDEX `fk_Empleado_Persona1_idx` (`emp_idPersona` ASC),
  INDEX `fk_Empleado_Sucursal1_idx` (`emp_idSucursal` ASC),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`emp_idPersona`)
    REFERENCES `deliverydb`.`Persona` (`pers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Sucursal1`
    FOREIGN KEY (`emp_idSucursal`)
    REFERENCES `deliverydb`.`Sucursal` (`suc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
